# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HXTakuAdapter-iOS-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HXTakuAdapter-iOS-Example
  pod 'AnyThinkiOS','6.3.75'
  pod 'HXSDK', '~> 4.4.0'

  target 'HXTakuAdapter-iOS-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HXTakuAdapter-iOS-ExampleUITests' do
    # Pods for testing
  end

end
